INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (222,'UA','EU','Украина','Ukraine',49,32,'Europe/Kiev');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (253,'BQ','NA','Бонэйр, Синт-Эстатиус и Саба','Bonaire, Saint Eustatius and Saba',12.21,-68.29,'America/Kralendijk');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (198,'SM','EU','Сан-Марино','San Marino',43.94,12.45,'Europe/San_Marino');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (59,'DM','NA','Доминика','Dominica',15.5,-61.33,'America/Dominica');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (23,'BF','AF','Буркина Фасо','Burkina Faso',12.5,-1.67,'Africa/Ouagadougou');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (145,'MQ','NA','Мартиника','Martinique',14.67,-61,'America/Martinique');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (45,'CK','OC','Острова Кука','Cook Islands',-21.25,-159.79,'Pacific/Rarotonga');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (13,'AR','SA','Аргентина','Argentina',-34,-64,'America/Argentina/Buenos_Aires');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (12,'AQ','AN','Антарктида','Antarctica',-82.68,8.79,NULL);
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (37,'BZ','NA','Белиз','Belize',17.25,-88.75,'America/Belize');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (27,'BJ','AF','Бенин','Benin',9.5,2.25,'Africa/Porto-Novo');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (76,'GA','AF','Габон','Gabon',-1,11.75,'Africa/Libreville');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (142,'MN','AS','Монголия','Mongolia',46,105,'Asia/Ulaanbaatar');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (14,'AS','OC','Американское Самоа','American Samoa',-14.23,-169.48,'Pacific/Pago_Pago');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (62,'EC','SA','Эквадор','Ecuador',-1.25,-78.25,'America/Guayaquil');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (58,'DK','EU','Дания','Denmark',56,10,'Europe/Copenhagen');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (200,'SO','AF','Сомали','Somalia',6,48,'Africa/Mogadishu');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (249,'IM','EU','Остров Мэн','Isle of Man',54.25,-4.5,'Europe/Isle_of_Man');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (18,'AZ','AS','Азербайджан','Azerbaijan',40.5,47.5,'Asia/Baku');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (152,'MX','NA','Мексика','Mexico',23,-102,'America/Mexico_City');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (232,'VI','NA','Виргинские Острова США','Virgin Islands of the United States',18.35,-64.98,'America/St_Thomas');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (192,'SG','AS','Сингапур','Singapore',1.37,103.8,'Asia/Singapore');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (51,'CU','NA','Куба','Cuba',22,-79.5,'America/Havana');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (166,'NZ','OC','Новая Зеландия','New Zealand',-42,174,'Pacific/Auckland');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (99,'HU','EU','Венгрия','Hungary',47,20,'Europe/Budapest');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (88,'GR','EU','Греция','Greece',39,22,'Europe/Athens');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (241,'ZM','AF','Замбия','Zambia',-14.33,28.5,'Africa/Lusaka');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (173,'PK','AS','Пакистан','Pakistan',30,70,'Asia/Karachi');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (156,'NC','OC','Новая Каледония','Nouvelle-Caledonie',-21.5,165.5,'Pacific/Noumea');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (125,'LC','NA','Святая Люсия','Saint Lucia',13.88,-60.97,'America/St_Lucia');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (68,'ET','AF','Эфиопия','Ethiopia',9,39.5,'Africa/Addis_Ababa');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (24,'BG','EU','Болгария','Bulgaria',42.67,25.25,'Europe/Sofia');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (153,'MY','AS','Малайзия','Malaysia',2.5,112.5,'Asia/Kuala_Lumpur');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (30,'BO','SA','Боливия','Bolivia',-17,-65,'America/La_Paz');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (113,'KG','AS','Кыргызстан','Kyrgyzstan',41.5,75,'Asia/Bishkek');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (132,'LV','EU','Латвия','Latvia',57,25,'Europe/Riga');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (119,'KR','AS','Южная Корея','South Korea',36.5,127.75,'Asia/Seoul');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (162,'NO','EU','Норвегия','Norway',62,10,'Europe/Oslo');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (238,'YT','AF','Майотта','Mayotte',-12.83,45.17,'Indian/Mayotte');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (15,'AT','EU','Австрия','Austria',47.33,13.33,'Europe/Vienna');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (209,'TG','AF','Того','Togo',8.67,1.08,'Africa/Lome');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (87,'GQ','AF','Экваториальная Гвинея','Equatorial Guinea',1.7,10.5,'Africa/Malabo');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (48,'CN','AS','Китай','China',35,105,'Asia/Shanghai');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (182,'QA','AS','Катар','Qatar',25.5,51.25,'Asia/Qatar');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (225,'US','NA','США','United States',39.76,-98.5,'America/New_York');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (178,'PS','AS','Палестина','Palestine',31.92,35.2,'Asia/Gaza');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (227,'UZ','AS','Узбекистан','Uzbekistan',41.67,63.83,'Asia/Tashkent');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (42,'CG','AF','Конго','Congo',-1,15.5,'Africa/Brazzaville');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (117,'KN','NA','Сент-Китс и Невис','Saint Kitts and Nevis',17.33,-62.75,'America/St_Kitts');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (128,'LR','AF','Либерия','Liberia',6.5,-9.5,'Africa/Monrovia');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (118,'KP','AS','Северная Корея','North Korea',40,127,'Asia/Pyongyang');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (196,'SK','EU','Словакия','Slovakia',48.67,19.5,'Europe/Bratislava');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (61,'DZ','AF','Алжир','Algeria',28,3,'Africa/Algiers');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (55,'CZ','EU','Чехия','Czech Republic',49.75,15,'Europe/Prague');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (252,'MF','NA','Сен-Мартен','Saint-Martin',18.07,-63.07,'America/Marigot');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (150,'MV','AS','Мальдивские острова','Maldives',3.2,73,'Indian/Maldives');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (141,'MM','AS','Мьянма','Burma',21,96,'Asia/Rangoon');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (207,'TD','AF','Чад','Chad',15,19,'Africa/Ndjamena');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (64,'EG','AF','Египет','Egypt',27,30,'Africa/Cairo');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (235,'WF','OC','Уоллис и Футуна','Wallis and Futuna',-13.3,-176.2,'Pacific/Wallis');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (110,'JO','AS','Иордания','Jordan',31,36,'Asia/Amman');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (120,'KW','AS','Кувейт','Kuwait',29.5,47.75,'Asia/Kuwait');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (229,'VC','NA','Сент-Винсент и Гренадины','Saint Vincent and the Grenadines',13.08,-61.2,'America/St_Vincent');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (202,'ST','AF','Сан-Томе и Принсипи','Sao Tome and Principe',1,7,'Africa/Sao_Tome');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (216,'TL','OC','Восточный Тимор','East Timor',-8.83,125.75,'Asia/Dili');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (73,'FO','EU','Фарерские острова','Faroe Islands',62,-7,'Atlantic/Faroe');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (56,'DE','EU','Германия','Germany',51.5,10.5,'Europe/Berlin');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (22,'BE','EU','Бельгия','Belgium',50.75,4.5,'Europe/Brussels');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (108,'IT','EU','Италия','Italia',42.83,12.83,'Europe/Rome');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (148,'MT','EU','Мальта','Malta',35.92,14.43,'Europe/Malta');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (38,'CA','NA','Канада','Canada',60.11,-113.64,'America/Toronto');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (176,'PN','OC','Питкэрн','Pitcairn Islands',-25.07,-130.1,'Pacific/Pitcairn');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (169,'PE','SA','Перу','Peru',-10,-75.25,'America/Lima');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (213,'TM','AS','Туркменистан','Turkmenistan',39.75,59.67,'Asia/Ashgabat');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (218,'TT','NA','Тринидад и Тобаго','Trinidad and Tobago',11,-61,'America/Port_of_Spain');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (190,'SD','AF','Судан','Sudan',16,30,'Africa/Khartoum');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (165,'NU','OC','Ниуэ','Niue',-19.03,-169.87,'Pacific/Niue');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (136,'MD','EU','Молдова','Moldova',47.25,28.58,'Europe/Chisinau');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (189,'SC','AF','Сейшеллы','Seychelles',-4.58,55.67,'Indian/Mahe');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (83,'GL','NA','Гренландия','Greenland',72,-40,'America/Godthab');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (5,'AF','AS','Афганистан','Afghanistan',33,66,'Asia/Kabul');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (171,'PG','OC','Папуа Новая Гвинея','Papua New Guinea',-6,147,'Pacific/Port_Moresby');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (40,'CD','AF','Демократическая Республика Конго','Democratic Republic of the Congo',-2.5,23.5,'Africa/Kinshasa');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (226,'UY','SA','Уругвай','Uruguay',-33,-56,'America/Montevideo');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (180,'PW','OC','Палау','Palau',7.5,134.62,'Pacific/Palau');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (155,'NA','AF','Намибия','Namibia',-22,17,'Africa/Windhoek');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (131,'LU','EU','Люксембург','Luxembourg',49.75,6.17,'Europe/Luxembourg');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (168,'PA','NA','Панама','Panama',9,-80,'America/Panama');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (35,'BW','AF','Ботсвана','Botswana',-22,24,'Africa/Gaborone');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (126,'LI','EU','Лихтенштейн','Liechtenstein',47.17,9.53,'Europe/Vaduz');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (208,'TF','AN','Французские Южные и Антарктические территории','Territory of the French Southern and Antarctic Lands',-43,67,'Indian/Kerguelen');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (11,'AO','AF','Ангола','Angola',-12.5,18.5,'Africa/Luanda');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (245,'XK','EU','Косово','Kosovo',42.58,20.92,'Europe/Belgrade');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (122,'KZ','AS','Казахстан','Kazakhstan',48,68,'Asia/Almaty');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (185,'RU','EU','Россия','Russia',60,100,'Europe/Moscow');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (123,'LA','AS','Лаос','Laos',18,105,'Asia/Vientiane');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (163,'NP','AS','Непал','Nepal',28,84,'Asia/Kathmandu');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (211,'TJ','AS','Таджикистан','Tajikistan',39,71,'Asia/Dushanbe');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (112,'KE','AF','Кения','Kenya',1,38,'Africa/Nairobi');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (177,'PR','NA','Пуэрто-Рико','Puerto Rico',18.25,-66.5,'America/Puerto_Rico');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (33,'BT','AS','Бутан','Bhutan',27.5,90.5,'Asia/Thimphu');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (174,'PL','EU','Польша','Poland',52,20,'Europe/Warsaw');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (236,'WS','OC','Самоа','Samoa',-13.8,-172.13,'Pacific/Apia');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (172,'PH','AS','Филиппины','Philippines',13,122,'Asia/Manila');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (248,'GG','EU','Гернси','Guernsey',49.45,-2.58,'Europe/Guernsey');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (17,'AW','NA','Аруба','Aruba',12.5,-69.97,'America/Aruba');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (96,'HN','NA','Гондурас','Honduras',15,-86.5,'America/Tegucigalpa');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (39,'CC','AS','Кокосовые острова','Cocos (Keeling) Islands',-12.16,96.87,'Indian/Cocos');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (188,'SB','OC','Соломоновы острова','Solomon Islands',-8,159,'Pacific/Guadalcanal');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (41,'CF','AF','Центрально-Африканская Республика','Central African Republic',7,21,'Africa/Bangui');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (170,'PF','OC','Французская Полинезия','Polynesie Francaise',-15,-140,'Pacific/Tahiti');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (181,'PY','SA','Парагвай','Paraguay',-23.33,-58,'America/Asuncion');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (230,'VE','SA','Венесуэла','Venezuela',8,-66,'America/Caracas');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (134,'MA','AF','Марокко','Morocco',32,-6,'Africa/Casablanca');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (124,'LB','AS','Ливан','Lebanon',33.83,35.83,'Asia/Beirut');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (93,'GY','SA','Гайана','Guyana',5,-59,'America/Guyana');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (127,'LK','AS','Шри-Ланка','Sri Lanka',7.75,80.75,'Asia/Colombo');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (26,'BI','AF','Бурунди','Burundi',-3.5,30,'Africa/Bujumbura');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (78,'GD','NA','Гренада','Grenada',12.12,-61.67,'America/Grenada');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (231,'VG','NA','Британские Виргинские острова','British Virgin Islands',18.5,-64.5,'America/Tortola');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (159,'NG','AF','Нигерия','Nigeria',10,8,'Africa/Lagos');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (203,'SV','NA','Сальвадор','El Salvador',13.83,-88.92,'America/El_Salvador');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (164,'NR','OC','Науру','Nauru',-0.52,166.93,'Pacific/Nauru');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (161,'NL','EU','Нидерланды','Netherlands',52.25,5.75,'Europe/Amsterdam');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (31,'BR','SA','Бразилия','Brazil',-10,-55,'America/Sao_Paulo');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (146,'MR','AF','Мавритания','Mauritania',20.25,-10.5,'Africa/Nouakchott');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (144,'MP','OC','Северные Марианские острова','Northern Mariana Islands',15.21,145.76,'Pacific/Saipan');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (47,'CM','AF','Камерун','Cameroon',6,12.5,'Africa/Douala');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (167,'OM','AS','Оман','Oman',21,57,'Asia/Muscat');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (143,'MO','AS','Макао','Macau',22.16,113.56,'Asia/Macau');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (85,'GN','AF','Гвинея','Guinea',10.83,-10.67,'Africa/Conakry');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (205,'SZ','AF','Свазиленд','Swaziland',-26.5,31.5,'Africa/Mbabane');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (106,'IR','AS','Иран','Iran',32,53,'Asia/Tehran');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (90,'GT','NA','Гватемала','Guatemala',15.5,-90.25,'America/Guatemala');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (115,'KI','OC','Кирибати','Kiribati',1.42,172.98,'Pacific/Tarawa');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (72,'FM','OC','Микронезия','Federated States of Micronesia',6.92,158.16,NULL);
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (220,'TW','AS','Тайвань','Taiwan',24,121,'Asia/Taipei');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (147,'MS','NA','Монтсеррат','Montserrat',16.75,-62.2,'America/Montserrat');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (154,'MZ','AF','Мозамбик','Mozambique',-18.25,35,'Africa/Maputo');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (98,'HT','NA','Гаити','Haiti',19,-72.42,'America/Port-au-Prince');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (94,'HK','AS','Гонконг','Hong Kong',22.25,114.17,'Asia/Hong_Kong');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (44,'CI','AF','Кот-д’Ивуар','Cote d''Ivoire',8,-5.5,'Africa/Abidjan');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (97,'HR','EU','Хорватия','Croatia',45.17,15.5,'Europe/Zagreb');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (103,'IN','AS','Индия','India',22,79,'Asia/Kolkata');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (107,'IS','EU','Исландия','Iceland',65,-18,'Atlantic/Reykjavik');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (81,'GH','AF','Гана','Ghana',8.1,-1.2,'Africa/Accra');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (32,'BS','NA','Багамские острова','Bahamas',25.04,-77.37,'America/Nassau');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (92,'GW','AF','Гвинея-Бисау','Guinea-Bissau',12,-15,'Africa/Bissau');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (52,'CV','AF','Кабо-Верде','Cabo Verde',16,-24,'Atlantic/Cape_Verde');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (191,'SE','EU','Швеция','Sweden',62,15,'Europe/Stockholm');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (114,'KH','AS','Камбоджа','Cambodia',13,105,'Asia/Phnom_Penh');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (82,'GI','EU','Гибралтар','Gibraltar',36.13,-5.35,'Europe/Gibraltar');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (20,'BB','NA','Барбадос','Barbados',13.17,-59.53,'America/Barbados');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (54,'CY','EU','Кипр','Cyprus',35,33,'Asia/Nicosia');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (36,'BY','EU','Беларусь','Belarus',53,28,'Europe/Minsk');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (254,'SS','AF','Южный Судан','South Sudan',7.5,30,'Africa/Juba');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (234,'VU','OC','Вануату','Vanuatu',-16,167,'Pacific/Efate');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (67,'ES','EU','Испания','Spain',40,-4,'Europe/Madrid');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (193,'SH','AF','Остров Святой Елены','Ascension, and Tristan da Cunha Saint Helena',-15.95,-5.7,'Atlantic/St_Helena');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (111,'JP','AS','Япония','Japan',35.69,139.75,'Asia/Tokyo');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (79,'GE','AS','Грузия','Georgia',42,43.5,'Asia/Tbilisi');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (157,'NE','AF','Нигер','Niger',18,9,'Africa/Niamey');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (237,'YE','AS','Йемен','Yemen',15.5,47.5,'Asia/Aden');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (183,'RE','AF','Реюньон','Reunion',-21.1,55.6,'Indian/Reunion');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (75,'SX','NA','Синт-Мартен','Sint Maarten',18.04,-63.07,'America/Lower_Princes');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (66,'ER','AF','Эритрея','Eritrea',15,39,'Africa/Asmara');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (104,'IO','AS','Британская территория в Индийском океане','British Indian Ocean Territory',-6,72,'Indian/Chagos');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (137,'MG','AF','Мадагаскар','Madagascar',-20,47,'Indian/Antananarivo');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (219,'TV','OC','Тувалу','Tuvalu',-8.52,179.14,'Pacific/Funafuti');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (212,'TK','OC','Токелау','Tokelau',-9.17,-171.83,'Pacific/Fakaofo');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (129,'LS','AF','Лесото','Lesotho',-29.5,28.25,'Africa/Maseru');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (175,'PM','NA','Сен-Пьер и Микелон','Saint-Pierre et Miquelon',46.83,-56.33,'America/Miquelon');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (105,'IQ','AS','Ирак','Iraq',33,44,'Asia/Baghdad');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (239,'RS','EU','Сербия','Serbia',44.82,20.46,'Europe/Belgrade');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (43,'CH','EU','Швейцария','Switzerland',47,8.01,'Europe/Zurich');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (140,'ML','AF','Мали','Mali',18,-2,'Africa/Bamako');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (221,'TZ','AF','Танзания','Tanzania',-6,35,'Africa/Dar_es_Salaam');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (197,'SL','AF','Сьерра-Леоне','Sierra Leone',8.5,-11.5,'Africa/Freetown');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (7,'AI','NA','Ангилья','Anguilla',18.22,-63.05,'America/Anguilla');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (184,'RO','EU','Румыния','Romania',46,25,'Europe/Bucharest');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (10,'CW','NA','Кюрасао','Curacao',12.17,-68.97,'America/Curacao');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (214,'TN','AF','Тунис','Tunisia',34,9,'Africa/Tunis');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (250,'JE','EU','Джерси','Jersey',49.22,-2.12,'Europe/Jersey');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (151,'MW','AF','Малави','Malawi',-13.5,34,'Africa/Blantyre');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (223,'UG','AF','Уганда','Uganda',1.25,32.5,'Africa/Kampala');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (19,'BA','EU','Босния и Герцеговина','Bosnia and Herzegovina',44.25,17.83,'Europe/Sarajevo');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (138,'MH','OC','Маршалловы острова','Marshall Islands',7.11,171.24,NULL);
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (74,'FR','EU','Франция','France',46,2,'Europe/Paris');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (57,'DJ','AF','Джибути','Djibouti',11.83,42.5,'Africa/Djibouti');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (25,'BH','AS','Бахрейн','Bahrain',26.03,50.55,'Asia/Bahrain');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (210,'TH','AS','Таиланд','Thailand',15.5,101,'Asia/Bangkok');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (160,'NI','NA','Никарагуа','Nicaragua',13,-85,'America/Managua');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (251,'BL','NA','Сен-Бартелеми','Saint-Barthelemy',17.9,-62.83,'America/St_Barthelemy');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (3,'AD','EU','Андорра','Andorra',42.55,1.58,'Europe/Andorra');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (133,'LY','AF','Ливия','Libya',28,17,'Africa/Tripoli');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (179,'PT','EU','Португалия','Portugal',39.69,-8.13,'Europe/Lisbon');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (16,'AU','OC','Австралия','Australia',-25,135,'Australia/Sydney');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (195,'SJ','EU','Свальбард и Ян-Майен','Svalbard and Jan Mayen',78,20,'Arctic/Longyearbyen');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (60,'DO','NA','Доминиканская республика','Dominican Republic',19,-70.67,'America/Santo_Domingo');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (139,'MK','EU','Македония','Macedonia',41.67,21.75,'Europe/Skopje');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (199,'SN','AF','Сенегал','Senegal',14.5,-14.25,'Africa/Dakar');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (149,'MU','AF','Маврикий','Mauritius',-20.3,57.58,'Indian/Mauritius');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (186,'RW','AF','Руанда','Rwanda',-2,30,'Africa/Kigali');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (21,'BD','AS','Бангладеш','Bangladesh',24,90,'Asia/Dhaka');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (8,'AL','EU','Албания','Albania',41,20,'Europe/Tirane');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (100,'ID','AS','Индонезия','Indonesia',-5,120,'Asia/Jakarta');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (71,'FK','SA','Фолклендские острова','Falkland Islands',-51.75,-59.17,'Atlantic/Stanley');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (121,'KY','NA','Каймановы острова','Cayman Islands',19.5,-80.67,'America/Cayman');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (215,'TO','OC','Тонга','Tonga',-20,-175,'Pacific/Tongatapu');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (242,'ME','EU','Черногория','Montenegro',42.75,19.25,'Europe/Podgorica');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (91,'GU','OC','Гуам','Guam',13.48,144.82,'Pacific/Guam');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (28,'BM','NA','Бермуды','Bermuda',32.33,-64.74,'Atlantic/Bermuda');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (69,'FI','EU','Финляндия','Finland',64,26,'Europe/Helsinki');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (70,'FJ','OC','Фиджи','Fiji',-18,178,'Pacific/Fiji');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (80,'GF','SA','Французская Гвинея','Guyane',4,-53,'America/Cayenne');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (63,'EE','EU','Эстония','Estonia',59,26,'Europe/Tallinn');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (247,'AX','EU','Аландские острова','Aland Islands',60.25,20,'Europe/Mariehamn');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (101,'IE','EU','Ирландия','Ireland',53,-8,'Europe/Dublin');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (158,'NF','OC','Норфолк','Norfolk Island',-29.03,167.95,'Pacific/Norfolk');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (130,'LT','EU','Литва','Lithuania',55.42,24,'Europe/Vilnius');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (224,'UM','OC','Внешние малые острова США','United States Minor Outlying Islands',5.88,-162.06,NULL);
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (49,'CO','SA','Колумбия','Colombia',4,-73.25,'America/Bogota');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (109,'JM','NA','Ямайка','Jamaica',18.17,-77.25,'America/Jamaica');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (204,'SY','AS','Сирия','Syria',35,38,'Asia/Damascus');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (46,'CL','SA','Чили','Chile',-30,-71,'America/Santiago');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (84,'GM','AF','Гамбия','Gambia',13.5,-15.5,'Africa/Banjul');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (243,'ZW','AF','Зимбабве','Zimbabwe',-19,29.75,'Africa/Harare');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (77,'GB','EU','Великобритания','United Kingdom',54.76,-2.7,'Europe/London');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (240,'ZA','AF','ЮАР','South Africa',-29,24,'Africa/Johannesburg');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (135,'MC','EU','Монако','Monaco',43.73,7.42,'Europe/Monaco');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (194,'SI','EU','Словения','Slovenia',46.08,15,'Europe/Ljubljana');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (4,'AE','AS','ОАЭ','United Arab Emirates',23.75,54.5,'Asia/Dubai');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (102,'IL','AS','Израиль','Israel',31.5,34.75,'Asia/Jerusalem');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (29,'BN','AS','Бруней','Brunei',4.5,114.67,'Asia/Brunei');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (50,'CR','NA','Коста-Рика','Costa Rica',10,-84,'America/Costa_Rica');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (86,'GP','NA','Гваделупа','Guadeloupe',16.25,-61.58,'America/Guadeloupe');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (6,'AG','NA','Антигуа и Барбуда','Antigua and Barbuda',17.05,-61.8,'America/Antigua');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (217,'TR','AS','Турция','Turkey',39,35,'Europe/Istanbul');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (89,'GS','AN','Южная Георгия и Южные Сандвичевы острова','South Georgia and the South Sandwich Islands',-56,-33,'Atlantic/South_Georgia');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (201,'SR','SA','Суринам','Suriname',4,-56,'America/Paramaribo');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (206,'TC','NA','Туркс и Кейкос','Turks and Caicos Islands',21.73,-71.58,'America/Grand_Turk');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (53,'CX','AS','Остров Рождества','Christmas Island',-10.5,105.67,'Indian/Christmas');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (116,'KM','AF','Коморские острова','Comoros',-12.23,44.45,'Indian/Comoro');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (233,'VN','AS','Вьетнам','Vietnam',16.17,107.83,'Asia/Ho_Chi_Minh');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (9,'AM','AS','Армения','Armenia',40.25,45,'Asia/Yerevan');
INSERT INTO sxgeo_country(id,iso,continent,name_ru,name_en,lat,lon,timezone) VALUES (228,'VA','EU','Ватикан','Vatican',41.9,12.45,'Europe/Vatican');
